name: Deploy Website
on: 
  push: 
    branches: 
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Lint Code
        run: npm run lint
      - name: Test Code
        run: npm test
  build:
    needs: test
    runs-on: ubuntu-latest 
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}   
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build Code
        run: npm run build
      - name: Publish JS filename
        id: publish
        run: find dist/assets/*.js -type f -execdir echo '::set-output name=script-file::{}' ';' 
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            dist
            package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Show Artifacts
        run: ls
      - name: Show File name
        run: echo "${{needs.build.outputs.script-file}}"
      - name: Deploy Code
        run: echo "Deplying..."
